### ISSUE TITLE
Can I separate this by modules?

### ISSUE THREAD

**Issue by marlester-dev** [hakan-krgn/spigot-injection#5]
I currently need only dependency injection

**Comment by hakan-krgn** [comment]
Have you tried to use dependency injection of spring boot? Because these annotations are so popular.
Also project size is not much, its just 180kb with all modules. But if you want to use just dependency injection, you can use core module. ``implementation 'com.github.hakan-krgn.spigot-injection:injection-core:0.1.2.4'``
